services:
#  ai-ollama: # HINT: uncomment to use ollama instead of mistral
#    build: .
#    container_name: ai-ollama
#    image: ollama/ollama
#    restart: unless-stopped
#    healthcheck:
#      test: ollama --version || exit 1
#      interval: 10s
#    ports:
#      - "11400:11434"
#    volumes:
#      - ./docker/ollama:/root/.ollama
  postgresql:
    container_name: ai-referential
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_DB: ai-referential
      POSTGRES_USER: gilles
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgresql-rag-data:/var/lib/postgresql/data/
  qdrant:
    container_name: ai-vectorestore
    image: qdrant/qdrant:latest
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    ports:
      - "6343:6333"
      - "6344:6334"
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - qdrant-rag-data:/qdrant/storage
volumes:
  postgresql-rag-data:
    name: postgresql-rag-data
    external: true
  qdrant-rag-data:
    name: qdrant-rag-data
    external: true
