spring:
  datasource:
    url: ${DB_JDBC_URL:jdbc:postgresql://localhost:5432/ai-referential}
    username: ${DB_JDBC_USERNAME:gilles}
    password: ${DB_JDBC_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  ai:
#    ollama: # HINT: uncomment to use ollama instead of mistral
#      base-url: http://localhost:11400
#      chat.options:
#        model: mistral
#        temperature: 0.7
    mistralai: # HINT: comment to use ollama instead of mistral
      api-key: ${MISTRALAI_API_KEY}
    vectorstore.qdrant:
      host: ${QDRANT_HOST:localhost}
      port: ${QDRANT_PORT:6334}
      collection-name: ai
      initialize-schema: true
  application.name: ai
  docker.compose:
    enabled: true
    lifecycle-management: start_and_stop
  liquibase.change-log: classpath:/db/changelog/db.changelog-master.yml
  threads.virtual.enabled: true
