logging.level:
  org.springframework.ai.chat.client.advisor: debug
spring:
  datasource:
    url: ${DB_JDBC_URL:jdbc:postgresql://localhost:5434/ai-referential}
    username: ${DB_JDBC_USERNAME:gilles}
    password: ${DB_JDBC_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  ai:
    vectorstore.qdrant:
      host: ${QDRANT_HOST:localhost}
      port: ${QDRANT_PORT:6344}
      collection-name: ai
      initialize-schema: true
  application.name: ai
  docker.compose:
    enabled: false # disabled because ollama requires to pull a model first
    lifecycle-management: start_and_stop
    file: compose.yaml
  liquibase.change-log: classpath:/db/changelog/db.changelog-master.yml
  shell.interactive.enabled: true
  threads.virtual.enabled: true
